- name: Change DB Owner on multiple SQL servers
  hosts: DEV_SQL
  gather_facts: no

  vars:
    sa_username: "{{ username }}"
    sa_password: "{{ password }}"
    source_DB_name: "{{ DatabaseName }}"
    new_dbowner_name: "{{ NewOwner }}"

  tasks:
    - name: Change DB owner using Invoke-Sqlcmd
      win_shell: |
        $query = @"
        USE [{{ source_DB_name }}];
        EXEC sp_changedbowner '{{ new_dbowner_name }}';
        "@
        Invoke-Sqlcmd -ServerInstance "{{ inventory_hostname }}" -Username "{{ sa_username }}" -Password "{{ sa_password }}" -Query $query -TrustServerCertificate
