- name: List of users/roles
  hosts: server

  vars:
    db_name: postgres
    login_user: "{{ user }}"
    login_password: "{{ login_password_var }}"
  tasks:
    - name: run sql
      postgresql_query:
        login_user: "{{ login_user }}"
        login_password: "{{ login_password }}"
        db: "{{ db_name }}"
        query: SELECT rolname FROM pg_roles
      register: sql_data
    - name: print
      ansible.builtin.debug:
        var: sql_data
