- name: List of users/roles
  hosts: server

  vars:
    db_name: postgres
  tasks:
    - name: run sql
      postgresql_query:
        login_user: postgres
        login_password: Wednesday@12
        db: "{{ db_name }}"
        query: SELECT rolname FROM pg_roles
      register: sql_data
    - name: print
      ansible.builtin.debug:
        var: sql_data
