---
#playbook for grand privileges in a particular Database
- hosts: server
  gather_facts: true
  vars:
    table_name: "{{ table_name }}"
    db_name: "{{ DATABASENAME }}"
    login_user: "{{ user }}"
    login_password: "{{ login_password_var }}"
  
  
  tasks:
    - name: Ensure psycopg2 library is installed for Python
      ansible.builtin.apt:
        name: python3-psycopg2 # Use the apt package name for psycopg2
        state: present
    - name: Run to get vacccum status of specified table 
      postgresql_query:
        db: "{{ db_name }}"
        login_user: "{{ login_user }}"
        login_password: "{{ login_password }}"
        query: "select last_vacuum from pg_stat_all_tables where relname = '{{ table_name }}';"
      register: sql_data
      
    - name: print
      ansible.builtin.debug:
        var: sql_data
